version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    target-branch: "sYn-local-config"
    allow:
      - dependency-type: "production"
    groups:
      production:
        patterns:
          - "*"
